use-sort:
    group:
        - _main
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the Form Bundle package
     *
     * Copyright (c) 2017 Fernando Sánchez Martñínez
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * @author Fernando Sánchez Martínez <fer@madforwebs.com>
     */
